Repository oSoc19/reliability-score-backend, pull requests merged in 2019-07, with the labels that each got.

#8 Build backend structure
  .gitignore
  Pipfile
  Pipfile.lock
  app.py
  irail-example.json
  prediction.py
  root.py
Labels: enhancement

#9 Added async HTTP request to iRail /connections
  app.py
  connections.py
Labels: enhancement

#15 Handle missing arguments connections
  connections.py
Labels: bug

#17 CI & deployment setup
  .travis-ci.yml
  Procfile
  app.py
Labels: CI

#18 Add station to URI scripts
  scripts/station_uris/README.md
  scripts/station_uris/station_to_uri.json
  scripts/station_uris/station_to_uri.py
  scripts/station_uris/unique_stations.json
  scripts/station_uris/unique_stations.py
Labels: enhancement

#14 Querying and grouping stops
  .gitignore
  Pipfile
  Pipfile.lock
  app.py
  connections.py
  predict.py
Labels: enhancement

#20 Add ML prediction script
  Pipfile
  Pipfile.lock
  app.py
  classifier.py
  scripts/make-prediction/predict.py
Labels: enhancement

#22 Added CORS headers
  connections.py
  root.py
Labels: bug

#21 Integrate ML with API
  app.py
  classifier.py
  connections.py
  root.py
Labels: enhancement

#26 Fixed crash when there are no vias
  connections.py
Labels: bug

#38 Fixed naming of the reliability_graph property
  connections.py
Labels: bug

#39 Add spreadsheet scripts
  Pipfile
  scripts/spreadsheets/check_files.py
  scripts/spreadsheets/convert.py
  scripts/spreadsheets/crawler.py
  scripts/spreadsheets/list_spreadsheets.csv
  scripts/spreadsheets/one_file.py
Labels: enhancement

#40 API docs
  README.md
Labels: documentation

#43 Redirect to our Github repo
  root.py
Labels: enhancement

#42 Machine Learning docs
  ml/README.md
  ml/train_model.ipynb
Labels: documentation

#44 Update feature list in train_model.ipynb notebook
  ml/train_model.ipynb
Labels: documentation

#41 add scripts docs
  scripts/README.md
  scripts/csv_splitter/README.md
  scripts/spreadsheets/README.md
  scripts/spreadsheets/check_files.py
  scripts/station_uris/README.md
Labels: documentation

#45 Add Python/dependency installation guide to README.md
  README.md
Labels: documentation

#46 Configurable Google Drive path constant
  ml/train_model.ipynb
Labels: enhancement

#47 ML README: features formatting and fix some datatypes
  ml/README.md
Labels: documentation

#49 Handle invalid vehicle IDs
  connections.py
Labels: bug

#54 Always show reliability data for vias
  connections.py
Labels: bug

#55 Return transfer_time in seconds
  connections.py
Labels: bug
